# Generated by Django 3.0 on 2019-12-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LR_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lrmachine',
            old_name='inpc',
            new_name='stock_symbol',
        ),
    ]
